### ISSUE TITLE
Version always comes from VERSION_NAME

### ISSUE THREAD

**Issue by benasher44** [vanniktech/gradle-maven-publish-plugin#121]
If at configure time you update `project.version` to be something like `"${VERSION_NAME}-${buildnumberorsomethingelse}"`, the artifacts still end up being published using `VERSION_NAME` (i.e. settting `project.version` has no effect).

I'm pretty sure it's because of https://github.com/vanniktech/gradle-maven-publish-plugin/blob/3c9e994418e1fd078db56d7d5b7e58fa0e83cb02/src/main/kotlin/com/vanniktech/maven/publish/MavenPublishPom.kt#L33

**Comment by vanniktech** [comment]
Yep sounds about right. I personally haven't had a user case for taking the `project.version`.

**Comment by benasher44** [comment]
In some of the IntelliJ project templates, project.version comes preset, which is how our team got to using/relying on it. Do you think it could make sense to accommodate that in this plugin somehow? Depending on your CI setup, there are good reasons to specify your version at configure time in gradle code.

**Comment by vanniktech** [comment]
Yeah. I'm thinking if `project.version` is set take it, otherwise VERSION_NAME. What do you think @gabrielittner ?

**Comment by gabrielittner** [comment]
We could also just use `project.version` when configuring the pom. When the plugin is applied we immediately set `project.version` to `VERSION_NAME` https://github.com/vanniktech/gradle-maven-publish-plugin/blob/master/src/main/kotlin/com/vanniktech/maven/publish/BaseMavenPublishPlugin.kt#L27
If we continue project.version instead of reading `VERSION_NAME` again it becomes overridable in build file.

**Comment by vanniktech** [comment]
Then let's do that.

**Comment by gabrielittner** [comment]
@benasher44 Your overridden `project.version` will be used in 0.10.0.

**Comment by benasher44** [comment]
Thanks!!
