### ISSUE TITLE
Kotlin JS publish failing with dokka warnings

### ISSUE THREAD

**Issue by rnett** [vanniktech/gradle-maven-publish-plugin#192]
Visible here: https://github.com/rnett/kotlin-js-action/runs/1892402407?check_suite_focus=true

Note that both `dokkaHtml` and `generatePomFileForMavenJsPublication` run fine alone, which is what makes me think it's an issue here rather than with dokka (as seen in kotlin/dokka#1479).

One possible cause is I'm using nodejs with `binaries.library()` (and IR), but that seems unlikely.

**Comment by gabrielittner** [comment]
For the publish failure:

> Execution failed for task ':publishMavenJsPublicationToLocalRepository'.
> Failed to publish publication 'mavenJs' to repository 'local'
> Invalid publication 'mavenJs': artifactId cannot be empty.

This is happening because you set the property to an empty string
https://github.com/rnett/kotlin-js-action/blob/main/gradle.properties#L4-L6 and then this part is running to late https://github.com/rnett/kotlin-js-action/blob/main/build.gradle.kts#L13-L15. The good news is that you can just remove the 3 properties and keep setting group and version like you do in the lines above. If you leave out the gradle properties the plugin uses project group/name/version by default

**Comment by gabrielittner** [comment]
I'm not sure about the dokka failure but since it's in their task I don't think the issue is on our side.

**Comment by rnett** [comment]
Huh nice, that works.  I had to do it that way in another project but I think that was with an older version.
