### ISSUE TITLE
No matching staging repository found

### ISSUE THREAD

**Issue by gsavvid** [vanniktech/gradle-maven-publish-plugin#202]
I only have one staging repository but still when I execute `./gradlew closeAndReleaseRepository` I get the following error:

> No matching staging repository found. You can can explicitly choose one by passing it as an option like this "./gradlew closeAndReleaseRepository --repository=comexample-123". Available repositories are: commyrepo-1000

I'm using version 0.14.2 of the plugin.

**Comment by gsavvid** [comment]
Any ideas here?

**Comment by gabrielittner** [comment]
When you log into Sonatype you see one? Are you on `s01.oss.sonatype.org` by chance?

**Comment by gsavvid** [comment]
Thank you for your reply, @gabrielittner. 

Yes, I do see exactly one and if I execute `./gradlew closeAndReleaseRepository --repository=blahblah-xxxx`, then it works just fine.

Not sure what `s01.oss.sonatype.org` so I guess the answer here is no. I'm on `https://oss.sonatype.org/#stagingRepositories`, if that's what you're asking.

**Comment by gabrielittner** [comment]
> Yes, I do see exactly one and if I execute ./gradlew closeAndReleaseRepository --repository=blahblah-xxxx, then it works just fine.

Since this is working, did you set the `stagingProfile` somehwere? Or a Gradle property called `SONATYPE_STAGING_PROFILE`? It's described in this part of the readme https://github.com/vanniktech/gradle-maven-publish-plugin#releasing

> Not sure what s01.oss.sonatype.org is so I guess the answer here is no. I'm on https://oss.sonatype.org/#stagingRepositories, if that's what you're asking.

Depending on when you registered you might have to use a different domain, which requires extra configuration. That doesn't seem to apply to you.

**Comment by gsavvid** [comment]
No, I haven't set `stagingProfile` anywhere and below are all my relevant Gradle properties.

![Screenshot 2021-03-21 at 13 33 07](https://user-images.githubusercontent.com/5520133/111905228-db83e800-8a4a-11eb-8749-4f5aae342d0e.png)

**Comment by gabrielittner** [comment]
I think I've figured out what's going on and it will be fixed in the next release.

**Comment by gsavvid** [comment]
Hi, @gabrielittner. Which version would that be? Version `0.14.2` seems to have been released 10 days ago and the changelog mentions `fix closeAndReleaseRepository requiring callers to pass --repository`. However, I've been using version `0.14.2` for more than a month now. 

So is this fixed in a new version which has the same name as the last one (ie. 0.14.2)?

**Comment by gsavvid** [comment]
So I deleted my Gradle cache and re-downloaded `0.14.2` and now I notice another issue: with every `./gradlew publish --no-daemon --no-parallel` two staging repositories are created for some reason. I drop them both, re-run the same gradle task and another two repositories are created.

**Comment by gsavvid** [comment]
Is there perhaps an older version that I could use in the meantime without that issue @gabrielittner?

**Comment by gabrielittner** [comment]
In regards to the 0.14.2 release date, it was published in February however I forgot to create a release on Github, so that's where the time difference comes from. The next release will be 0.15.0.

For 2 repositories getting created: Since you are using `--no-parallel` I'm not sure what's going. The uploading part is done on Gradle's side so maybe updating Gradle helps if you are not on the latest version
