### ISSUE TITLE
401 - Unauthorized Error

### ISSUE THREAD

**Issue by svignesh93** [vanniktech/gradle-maven-publish-plugin#203]
401 - Unauthorized Error when using "mavenCentralRepositoryUsername" and "mavenCentralRepositoryPassword" in gradle.properties from gradle home directory.

But it works with "SONATYPE_NEXUS_USERNAME" and "SONATYPE_NEXUS_PASSWORD"

**Comment by YahiaAngelo** [comment]
> 
> 
> 401 - Unauthorized Error when using "mavenCentralRepositoryUsername" and "mavenCentralRepositoryPassword" in gradle.properties from gradle home directory.
> 
> But it works with "SONATYPE_NEXUS_USERNAME" and "SONATYPE_NEXUS_PASSWORD"

I can confirm that it's working with "SONATYPE_NEXUS_USERNAME" and "SONATYPE_NEXUS_PASSWORD".
Otherwise it says 401 - Unauthorized

**Comment by svignesh93** [comment]
@YahiaAngelo thanks for confirming, I think updating readme.md file would be great and would fix this problem. I followed the steps provided and spent 2 days finding the root cause and finally found the key from the code.

**Comment by debuglevel** [comment]
Same for environment variables. But the problem might rather be that GitHub always shows the `README.md` of `HEAD` instead of the latest release (`0.13.0`); and their naming changed.

1. It's always curious when naming of an env changes without fallback to the old scheme.
2. `mavenCentralRepositoryUsername` is a rather uncommon naming scheme for an env; all uppercase with underscores was far more usual.

**Comment by gabrielittner** [comment]
The latest release is `0.14.2` and the new property names were introduced in 0.14.0. One note for

> It's always curious when naming of an env changes without fallback to the old scheme.

0.14.x does have a fallback to the old names and prints a deprecation warning. The fallback will be removed in 0.15.0 and changed to an error.

> mavenCentralRepositoryUsername is a rather uncommon naming scheme for an env; all uppercase with underscores was far more usual.

The naming scheme comes from Gradle's credentials API that was introduced in Gradle 6.6 https://docs.gradle.org/6.6/release-notes.html#credentials
https://docs.gradle.org/6.6/samples/sample_publishing_credentials.html

**Comment by gabrielittner** [comment]
I can't reproduce this. Please make sure you are on version `0.14.x`. If this is still happening it would be great if you could share a project

**Comment by radekkozak** [comment]
Hi everyone,
unfortunately i'm on the newest 0.19.0 version and still getting 401 Unathorized Error 
"Could not PUT 'https://oss.sonatype.org/content/repositories/snapshots/{my coordinates here}/maven-metadata.xml'. Received status code 401 from server: Unauthorized"

I'm using regular oss.sonatype.org server not s01 per sonatype's info (i have this repo from before s01 was introduced for new users)

i'm using "mavenCentralRepositoryUsername" and "mavenCentralRepositoryPassword" - CREDENTIALS are 100% OK - and this is the weirdest thing - even with this error the Staging Repositories on Sonatype are made correctly and Releasing works. But i kinda need to have this working properly for CI sake  because gradle execution fails with this 

@YahiaAngelo @svignesh93 Yahia, Vignesh - you mentioned guys it's working properly with earlier "SONATYPE_NEXUS_USERNAME" and "SONATYPE_NEXUS_PASSWORD" 

BUT they were removed in newest releases and even when reverting back to 0.14.2 version i still got this error. 
With what version you got this working guys? and do you have s01 or regular sonatype repos ?

Thanks in advance for any info on this /cc @gabrielittner
