### ISSUE TITLE
[Dokka 1.4.30] Could not create domain object 'androidTestRelease' (GradleDokkaSourceSetBuilder)

### ISSUE THREAD

**Issue by chrisbanes** [vanniktech/gradle-maven-publish-plugin#208]
Unfortunately it seems that `gradle-maven-publish-plugin` doesn't work with the new Dokka 1.4.30.

_Stack trace incoming_

**Comment by gabrielittner** [comment]
Thanks for reporting it. A strack trace would be useful because we don't interact much with the plugin anymore. All we really do is finding a `DokkaTask` and using that as input for a jar task.

https://github.com/vanniktech/gradle-maven-publish-plugin/blob/master/src/main/kotlin/com/vanniktech/maven/publish/ProjectExtensions.kt#L26-L32
https://github.com/vanniktech/gradle-maven-publish-plugin/blob/master/src/main/kotlin/com/vanniktech/maven/publish/tasks/JavadocsJar.kt

**Comment by chrisbanes** [comment]
Woops, this was actually an issue in my config. Sorry for the false alarm.
