### ISSUE TITLE
How to publish to Sonatype snapshots?

### ISSUE THREAD

**Issue by akarnokd** [vanniktech/gradle-maven-publish-plugin#238]
Hi.

Bintray has gone away and our (RxJava) Artifactory snapshot uploads stopped working. It seems Sonatype/Nexus has its own snapshot upload capability, but I haven't found much details on how to enable this with the plugin.

Is it a matter of just letting the plugin run with `-SNAPSHOT` as the `VERSION_NAME` or do I have to configure plugin with the sonatype snapshot url (i.e., [like this](https://central.sonatype.org/publish/publish-gradle/))? 

~~I can see the plugin itself has snapshots on Nexus. Did you have to contact their support to get it enabled for you or it is just a matter of publishing?~~ **Edit**: I'd guess snapshots have been automatically enabled when creating the repo. Needs testing though.

**Comment by akarnokd** [comment]
I worked it out: conditionally retarget the url:

```groovy
if (version.endsWith("-SNAPSHOT")) {
      
      publishing {
        repositories {
          maven {
             url = "https://s01.oss.sonatype.org/content/repositories/snapshots/"
          }
        }
      }
  // ...
}

**Comment by gabrielittner** [comment]
@akarnokd just as an fyi, we also configure the default `mavenCentral` repository that we create to publish to Sonatype's snapshot repository instead of the staging repository when the version ends with `-SNAPSHOT`. So you should be able to just run the same publish task for publishing snapshots and releases. There is nothing wrong with what you're doing though
