### ISSUE TITLE
AGP 7.1 supports javadocJar, sourcesJar and variant publishing

### ISSUE THREAD

**Issue by TWiStErRob** [vanniktech/gradle-maven-publish-plugin#332]
Hi, I just read these 3 release notes, I thought I would call it out:
https://developer.android.com/studio/releases/gradle-plugin#build-variant-publishing

Does this mean most of this plugin can be replaced with standard Gradle publishing / AGP configuration?

See also https://developer.android.com/studio/build/maven-publish-plugin

**Comment by gabrielittner** [comment]
This plugin builds on top of the new APIs the same way it was built on top of the old APIs. The main difference now is that we need to do less here since AGP will create the javadoc jar and sources jar for us. It definitely has gotten easier to replace this plugin now with just configuring it yourself but I think there is still value here

- you don't need to know how the publishing needs to be configured, which is [this for AGP](https://github.com/vanniktech/gradle-maven-publish-plugin/blob/master/plugin/src/main/kotlin/com/vanniktech/maven/publish/Platform.kt#L192-L211) plus configuring configuring to [publish to maven central](https://github.com/vanniktech/gradle-maven-publish-plugin/blob/master/plugin/src/main/kotlin/com/vanniktech/maven/publish/MavenPublishBaseExtension.kt#L51-L68), [signing](https://github.com/vanniktech/gradle-maven-publish-plugin/blob/master/plugin/src/main/kotlin/com/vanniktech/maven/publish/MavenPublishBaseExtension.kt#L114-L124) and filling the [pom](https://github.com/vanniktech/gradle-maven-publish-plugin/blob/master/plugin/src/main/kotlin/com/vanniktech/maven/publish/MavenPublishBaseExtension.kt#L153-L222)
- the plugin offers a unified API regardless of what you want to publish, so you don't need to care about whether you have an Android, a Java, a Kotlin multiplatform library or a Gradle plugin
- convenience features like Gradle properties for pom values or easy configuration for in memory signing keys

**Comment by gabrielittner** [comment]
Keeping this open to improve the docs in this regard

**Comment by TWiStErRob** [comment]
Nice on @gabrielittner!

**Comment by gabrielittner** [comment]
The readme and [website](https://vanniktech.github.io/gradle-maven-publish-plugin/#advantages-over-maven-publish) now have a section about the advantages of this plugin over just using maven-publish
