### ISSUE TITLE
`closeAndReleaseRepository` fails because `publish` creates multiple staging repositories

### ISSUE THREAD

**Issue by eygraber** [vanniktech/gradle-maven-publish-plugin#381]
I have a CI task that runs `./gradlew publish && ./gradlew closeAndReleaseRepository`.

This usually works, but I just ran into [a CI error](https://github.com/eygraber/gradle-utils/runs/7738714637?check_suite_focus=true#step:7:265):

```
More than 1 matching staging repository found in account ***. You can can explicitly choose one by passing it as an option like this "./gradlew closeAndReleaseRepository --repository comexample-123". Available repositories are: com***-1119, com***-1120
```

I confirmed that there were two staging repositories created, and they were both created by the `publish` task.

**Comment by vanniktech** [comment]
I also had this once but it was since I was doing 2 releases of different repositories simultaneously.

**Comment by eygraber** [comment]
In this case there was only 1 release happening.

It looks like the [gradle-nexus](https://github.com/gradle-nexus/publish-plugin/blob/master/src/main/kotlin/io/github/gradlenexus/publishplugin/InitializeNexusStagingRepository.kt) creates a staging repo for each build, but you have to use their lifecycle task instead of the built in gradle ones.

This plugin could accomplish something similar, while retaining the ability to just use the gradle publish tasks by:

1. Make an initialization task that creates a staging repo
  a. Call `GET profiles` and find the `name` that matches the project's `group` and get its `id`
  b. Call `POST profiles/<id>/start` to create a repo, using the project's GAV or a unique user override for the `description` field
  c. Get the `stagedRepositoryId` from the response, and use that to set the repo url (via a property)
2. Make the gradle publish tasks depend on the initialization task
3. Make the `closeAndReleaseRepository` task depend on the gradle publish tasks 
  a. Call `GET profile_repositories` and find the matching description
  b. If there is 0 or more than 1 matching, error
  c. Otherwise close and release :smile:

**Comment by eygraber** [comment]
In any case, the specific issue here seems to be that after adding a new gradle project, all artifacts are put into one staging repo, and one pom file from one of the projects are put into a separate staging repo.

I have no idea what is causing this. I reached out to Sonatype to see if it is an issue on their end. The only clue I have is that the pom file is always from a gradle plugin that I'm publishing.

**Comment by eygraber** [comment]
And now I ran it a bunch of time and it suddenly worked ¯\_(ツ)_/¯

**Comment by gabrielittner** [comment]
One workaround is to run publishToMavenLocal first so that everything is already built and that the actual publish call only uploads the artifacts. That seems to decrease the likelihood of this happening, probably because there is less time between the uploads

**Comment by eygraber** [comment]
Interesting, I'll try that out.

Any thoughts on creating a staging repo per publish?

**Comment by gabrielittner** [comment]
Yes, that would definitely be an useful addition. I'll try to look at it when I have some time

**Comment by beyondeye** [comment]
> And now I ran it a bunch of time and it suddenly worked ¯\_(ツ)_/¯

I have also this issue. what do you mean running several time? running the publish task several times without dropping from sonatype the splitted staging repositories?

**Comment by beyondeye** [comment]
I have now tried the "publishToMavenLocal first" trick and did not work.

Then I tried to run the "publish" task multiple times, and then selecting manually in nexus repository manager the first staging repository of the multiple ones that have been created by the plugin and manually "close" and then "release' it.

 This apparently worked. The first of the multiple staging repositories contains most of the files needed for release, while the other ones contain only aar files for -android and android-debug variants of the libraries (I am publishing a multiplatform library: here is the [source](https://github.com/beyondeye/compose_bloc))

**Comment by gabrielittner** [comment]
Just as an update, I've started working on explicitly creating a staging repository in the plugin that we can publish to explicitly.

**Comment by gabrielittner** [comment]
This should be fixed in the latest snapshot, would be awesome if some of you could give it a try.

Running `./gradlew publish` or `./gradlew publishAllPublicationsToMavenCentralRepository` will internally create a new staging repository and make the publish tasks upload all artifacts to it. At the end of the build the repository will be closed automatically. For releasing  the repository you can either set `SONATYPE_AUTOMATIC_RELEASE` to `true` (this will then release the repo as part of executing the publish task) or run `closeAndReleaseRepository` like before.

```
./gradlew publish -PSONATYPE_AUTOMATIC_RELEASE=true
```
or 
```
./gradlew publish 
./gradlew closeAndReleaseRepository
```

**Comment by eygraber** [comment]
Getting an error

> Could not create an instance of type com.vanniktech.maven.publish.sonatype.SonatypeRepositoryBuildService.
> Cannot query the value of this property because it has no value available.

https://scans.gradle.com/s/hmkx6uxtwj2vu/failure#1

**Comment by gabrielittner** [comment]
New snapshot with the fix is available

**Comment by eygraber** [comment]
Does `SONATYPE_AUTOMATIC_RELEASE` only work with `publish` and not `publishAllPublicationsToMavenCentralRepository`? I set it here, but it didn't release - https://github.com/eygraber/uri-kmp/runs/8193844949?check_suite_focus=true#step:7:55

Also is there any way to cleanup created staging repos on a failure?

**Comment by gabrielittner** [comment]
My bad you are using `publishToMavenCentral(SonatypeHost.S01)` so instead of setting it as a property you need to pass `true` as a second parameter to it. `SONATYPE_AUTOMATIC_RELEASE` is meant to be used in combination with `SONATYPE_HOST`. 

> Also is there any way to cleanup created staging repos on a failure?

Yes, we should be able to do that. We are already detecting whether a task fails so that we skip the close and release at the end of the build, we should be able to call [drop](https://oss.sonatype.org/nexus-staging-plugin/default/docs/path__staging_profiles_-profileIdKey-_drop.html) in that case. Would you mind opening an issue for it?

**Comment by eygraber** [comment]
OK I'll try that now. I keep getting bitten by the `SonatypeHost.S01` thing with a bunch of issues :see_no_evil: 

I'll open an issue for dropping staging repos on failure.

**Comment by eygraber** [comment]
I see that the staging repo is being created based on the project group, but I have some scenarios where the same project group is used across builds that are happening in parallel. For example when building a kmp library that uses all targets, I build the windows artifacts on a windows machine, and everything else on a mac machine, and they both run at the same time. I imagine there could be some issues there. I could make them serial, but that would significantly slow down the release process.

**Comment by gabrielittner** [comment]
You should be able to run the in parallel. Sonatype Nexus has this concept of staging profiles and those basically match the groupIds you are allowed to publish to. So for example if you have the `com.example` staging profile in your account you can publish to `com.example` and also to variations of that like `com.example.foo`. What we are using the group id for is to find the staging profile in your account. We need to do that because a staging repo is created in a profile (the repo id will also derived from that like `comexample-123`). The plugin will create a staing repo with the `createStagingRepository` task and then will remember the id of that created repo for the rest of the build. That id is used for publishing to the repo, closing and releasing it. So even if you have 2 builds running in parallel they each create their own repository and will only publish to the one they created.

Side note: I forgot which Kotlin version introduced but you can build/publish kmp windows artifacts from

**Comment by gabrielittner** [comment]
> the task was only creating a new repo if it didn't find an already existing one

That part is there so that each build only creates one staging repo. In a multi project build where all projects apply the publish plugin each of them has a create task. We use the build service to share the result of whichever of the create tasks runs first with the others and use Gradle to make sure that the create tasks don't run in parallel. So the first one will actually create it, the others will just retrieve the id from the build service, but all of this is scoped to a single build

**Comment by eygraber** [comment]
Got the auto release working in one of my repos. Looks great, thanks!

**Comment by rozhok** [comment]
How can I use the snapshot? I've stumbled upon the same issue and need a fix. Looks like 0.21.0 is not working.
My `gradle.properties`:
```
SONATYPE_HOST=S01
SONATYPE_AUTOMATIC_RELEASE=true
RELEASE_SIGNING_ENABLED=true
```

I'm using groovy configuration.
Does `apply plugin: "com.vanniktech.maven.publish"` and `./gradlew publishAllPublicationsToMavenCentralRepository` will do the trick?

**Comment by rozhok** [comment]
Got it. 

In `settings.gradle`:

```groovy
pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
    }
}
```

In `build.gradle`:
```groovy
plugins {
    id "com.vanniktech.maven.publish" version "0.22.0-SNAPSHOT" apply false
}
```

**Comment by rozhok** [comment]
Everything is working fine, thank you folks for raising the issue and providing the fix :muscle:

**Comment by gabrielittner** [comment]
Glad to hear that it works well for you 👍
