### ISSUE TITLE
How to configure this plugin?

### ISSUE THREAD

**Issue by palexdev** [vanniktech/gradle-maven-publish-plugin#505]
Why is this plugin so hard to use in the latest versions?

Using:
```groovy
java {
    withSourcesJar()
    withJavadocJar()
    tasks.withType(Jar).each { it.archiveBaseName.set("aName") }
}
```
doesn't work as now the plugin generates its own archives (why?)

Using:
```groovy
javaSourcesJar {
  // Set archive name
}
```
is not possible as it doesn't appear to be a closure, and ends up with exception.

Configuring the `mavenPublishing{}`  as described in the docs seems to be not possible as `JavaLibrary` doesn't exist...

Saying that the current documentation is lacking is a compliment, can you improve it please?

**Workaround 1**
Sources and Javadoc jars generation can be disabled by using these lines of code:
```groovy
tasks.whenTaskAdded {task ->
    if(task.name.contains("javaSourcesJar") || task.name.contains("simpleJavadocJar")) {
        task.enabled = false
    }
}
```
Then you can use the `withSourcesJar()` and `withJavadocJar()` configs provided by Gradle.

**Workaround 2**
If the above method causes you troubles, like other tasks failing, you can try with this one instead:
```groovy
gradle.taskGraph.whenReady { graph ->
    if (graph.hasTask(javaSourcesJar)) {
        javaSourcesJar.enabled = false
    }
    if (graph.hasTask(simpleJavadocJar)) {
        simpleJavadocJar.enabled = false
    }
}
```

**Comment by gabrielittner** [comment]
Can you share more info on what you are trying to publish as well as your config?

**Comment by palexdev** [comment]
It's a bit hard to share it here as there are 5 modules in total, each of them is a separate publication of course, the project is here, [MaterialFX](https://github.com/palexdev/MaterialFX/tree/rewrite)

I think I also have another issue. The main mocule called 'components' can also produce a shadow jar, which I'd like to publish as well as a separate artifact.
The maven publish plugin allows to define custom publications with different coordinates, it's not possible with this plugin right? So the only solution that comes to my mind is to have a separate Gradle module that only produces the shadow jar and defines its coordinates, I'll try and report

**Comment by gabrielittner** [comment]
Thanks for sharing. 
 
```
java {
    withSourcesJar()
    withJavadocJar()
    tasks.withType(Jar).each { it.archiveBaseName.set("aName") }
}
```

For `archiveBaseName` it depends on what you want to achieve with it but it is generally not considered for publishing, not even by Gradle itself afaik.

You generally don't need `withSourcesJar()` and `withJavadocJar()` because the plugin creates adds a sources and javadoc jar automatically. With 0.24.0 the sources jar is actually added by using `withSourcesJar()` as well, that we had our own task was mostly legacy. For the javadoc jar we still have our own task mostly because we have some options (like using dokka as input for Kotlin projects), but for regular projects we will simply use the default `javadoc` task from Gradle as input so the the end result should be the same, if it isn't this is a bug.

If you still want to have to use the default `withJavadocJar()` your best choice is to use the base plugin with `configure(JavaLibrary(JavadocJar.None(), true)`. Note that you also need to add `pomFromGradleProperties()` to `mavenPublishing` when using the base plugin, otherwise your gradle.properties values won't be picked up.

> Configuring the mavenPublishing{} as described in the docs seems to be not possible as JavaLibrary doesn't exist...

You need to import `JavaLibrary` in the same way you imported `SonatypeHost` (JavadocJar too). This is missing in the docs and I'll add it.

> I think I also have another issue. The main module called 'components' can also produce a shadow jar, which I'd like to publish as well as a separate artifact.
> The maven publish plugin allows to define custom publications with different coordinates, it's not possible with this plugin right? So the only solution that comes to my mind is to have a separate Gradle module that only produces the shadow jar and defines its coordinates, I'll try and report

Having a separate artifact for that might be the best idea. 

Generally it should also be possible that you add another publication manually with the standard Gradle APIs. Things like the pom configuration from Gradle properties, signing and uploading will consider all publications anyways. The one area where you might run into issues is the artifact id which the plugin might overwrite which would result in both publications having the same coordinates.

**Comment by palexdev** [comment]
> For archiveBaseName it depends on what you want to achieve with it but it is generally not considered for publishing, not even by Gradle itself afaik.

If I comment the code, these are the generated artifacts:
![image](https://user-images.githubusercontent.com/16880178/218468787-212008d1-c77a-4696-97cd-2d85c13610b7.png)
And these are the ones generated with the `archiveBaseName` set:
![image](https://user-images.githubusercontent.com/16880178/218468971-7a1222a4-cacd-4473-b306-245136d4f491.png)


As you can see, the option is clearly not ignored. And as I said before, the plugin doesn't allow configuring the tasks to change the archive name.

**Comment by gabrielittner** [comment]
I might be used for the names of the files in the build file but from a publishing perspective it is ignored/not used. 

Here is an example of the same module published with `./gradlew publishToMavenLocal` after removing `archivesBaseName`:
<img width="693" alt="Screenshot 2023-02-14 at 21 52 49" src="https://user-images.githubusercontent.com/1358105/218860753-a0bf7ee7-1d1f-4789-9d7d-96e32e800915.png">
This would be the same when not using this plugin and using Gradle's regular publishing APIs.

Just to be clear, I'm not saying you shouldn't set `archivesBaseName`, just that it doesn't do anything for publishing and I'm only mentioning this because it was in the snippet in the original post.

**Comment by palexdev** [comment]
Oooh now I see
So in the build directory it actually matters, but in the local Maven cache (and then online) it doesn't

Now that's confusing more than I thought it would be lol
I suppose I can close this then, thank you for the support
