### ISSUE TITLE
How to config the name of publication

### ISSUE THREAD

**Issue by NamekMaster** [vanniktech/gradle-maven-publish-plugin#523]
It seems the publication name is hard code to `maven` in here: https://github.com/vanniktech/gradle-maven-publish-plugin/blob/main/plugin/src/main/kotlin/com/vanniktech/maven/publish/Platform.kt#L422. Is there any way to change this?
For example:
Current task name is: `publishManvePublicationToMyRepoRepository`, I want to change it to `publishReleasePublicationToMyRepoRepository`.

**Comment by gabrielittner** [comment]
What is your usecase for changing the publication name? The main reason why we don't have an option for this is that we don't manage all publications (some are created by Gradle or Kotlin) and I'm expecting the number of these to become higher over time.

**Comment by NamekMaster** [comment]
@gabrielittner on my case, the jenkins Job need to run a task called`publishReleasePublicationToMyRepoRepository`, and for some reason it cannot be configured or changed. Now I'm using a workaround by creating a new task with this name depends on `publishManvePublicationToMyRepoRepository `. I think it's better to let the user decide what name should be used. 
And you said:
>  we don't manage all publications 

I think it doesn't matter about managing publications. It's just a name.

**Comment by gabrielittner** [comment]
> I think it doesn't matter about managing publications. It's just a name.

It matters because whoever creates the publication controls the name, so we can't decide on a name for those. Because of that I don't want to make it configurable for the rest either. If a publication that we are creating right now would get created by Gradle in the future our API for this would need to be broken. 

As a workaround for your use case you can register a task with the wanted name and then make the real publishing task depend on that one.
