### ISSUE TITLE
Snapshot not uploading sources and javadocs

### ISSUE THREAD

**Issue by mzestars** [vanniktech/gradle-maven-publish-plugin#54]
Hi, I've used the 0.8.0 version of the library and the sources and javadocs was uploaded but there is no kotlin source code in the sources.jar.

Then, I've tested the snapshot version 0.9.0-SNAPSHOT, the kotlin source code is included in the sources.jar but this time the sources and javadocs jars are not being uploaded to the repo.

Maybe there's some code you've deleted while fixing the kotlin source code issue that caused the jars not being uploaded?

**Comment by mzestars** [comment]
Ok, I just looked at the source code and found out that the sources and javadocs upload task is only added if the androidSourcesJar and androidJavadocsJar is run explicitly. Thus the command is:

`./gradlew androidSourcesJar androidJavadocsJar uploadArchives --no-daemon --no-parallel`

instead of

`./gradlew uploadArchives --no-daemon --no-parallel`

**Comment by vanniktech** [comment]
Huh maybe we should always run them if you execute `uploadArchives`?

**Comment by mzestars** [comment]
I think having the option of not uploading them is good. Should stick with:

`./gradlew androidSourcesJar androidJavadocsJar uploadArchives --no-daemon --no-parallel`

Just that maybe u can mention this when 0.9.0 goes live. Thank u so much for an awesome library. :)

**Comment by vanniktech** [comment]
Interesting. Do you get sources and javadocs when running version 0.8.0 with `./gradlew uploadArchives --no-daemon --no-parallel`?

**Comment by martinbonnin** [comment]
I can reproduce the same behavior on a pure kotlin project (no android). I can include the sources + javadoc on 0.9.0-SNAPSHOT by doing `./gradlew kotlinSourcesJar javadocsJar uploadArchives --no-daemon --no-parallel`.

Running `./gradlew uploadArchives --no-daemon --no-parallel` with version 0.8.0 also includes sources + javadoc

**Comment by vanniktech** [comment]
My hunch is that the task configuration avoidance in #46 introduced this.

**Comment by martinbonnin** [comment]
I'd still vote to include sources and javadoc by default and not having to opt-in on the command line. Since Sonatype OSS is the default repository and they enforce sources and javadoc, it would make sens for the defaults to be consistent

**Comment by vanniktech** [comment]
Yes. Definitely, a regression that needs to be fixed before we publish 0.9.0

**Comment by bendb-instacart** [comment]
I can easily believe that task-configuration-avoidance is the issue here.  It doesn't play well with AGP which is primarily built up after configuration.  I tried adopting it in dexcount-gradle-plugin and ended up abandoning the effort due to issues like this one.

It can probably be made to work but is difficult.  It may be simpler to just take the configuration hit.  Users (like myself) can always just conditionally apply this plugin, e.g.

```
if (Gradle.startParameter.taskNames.contains("uploadArchives") {
  apply plugin: "com.vanniktech.maven.publish"
}
```

**Comment by gabrielittner** [comment]
The issue is indeed the missing task configuration. The issue is that this change https://github.com/vanniktech/gradle-maven-publish-plugin/pull/46/files#diff-406fe0b4199eaa97bca99d8d9ffd96d0L115-L119 moves the addition of the artifacts to the task configuration. The javadoc/source artifacts will only be added when the task is configured, however the addition was wat automatically set up the task dependency from uploadArchives to the javadoc/source task. Without this dependency they will never be configured so their output won't get published.

**Comment by gabrielittner** [comment]
Should be fixed in the latest snapshot that was just published. If you're still seeing this issue please let me know

**Comment by zach-klippenstein** [comment]
Seems like sources are being published now! Thanks for the fix!
