### ISSUE TITLE
Signing task created immediately according to build scans

### ISSUE THREAD

**Issue by jrodbx** [vanniktech/gradle-maven-publish-plugin#578]
<img width="1002" alt="Screen Shot 2023-05-18 at 1 28 15 PM" src="https://github.com/vanniktech/gradle-maven-publish-plugin/assets/1868149/cda642d3-acd4-4cdf-b28d-390e9b1eff08">

Looks like using [NamedDomainObjectCollection.findByName(java.lang.String)](https://docs.gradle.org/current/javadoc/org/gradle/api/NamedDomainObjectCollection.html#findByName-java.lang.String-) is the root cause: https://github.com/vanniktech/gradle-maven-publish-plugin/blob/ebb6e0d494d50c658f82d11851e3c1f9875df3ed/plugin/src/main/kotlin/com/vanniktech/maven/publish/MavenPublishBaseExtension.kt#L134

I tried migrating to [TaskCollection.named(java.lang.String)](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/TaskCollection.html#named-java.lang.String-) per the advice [here](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html#sec:old_vs_new_configuration_api_overview) along with wrapping it in a try catch, but integration tests with Gradle 7 and AGP < 8 started failing.

To repro:

```
git clone https://github.com/cashapp/paparazzi.git
cd paparazzi
./gradlew test --scan
```

Then click on resulting build scan, go to Performance -> Configuration and look at in the bottom section for rows with N tasks created in the rightmost column.  If you expand the row (note the chevron on the element in the *leftmost* column in a given row) then hover over that element to find and tap to show the overlay, you will see that signMavenPublication is "created immediately".

**Comment by gabrielittner** [comment]
Unfortunately Gradle itself is [creating the signing task eagerly](https://github.com/gradle/gradle/blob/mai/subprojects/signing/src/main/java/org/gradle/plugins/signing/SigningExtension.java#L413). 
There is already a [Gradle issue](https://github.com/gradle/gradle/issues/18477) for it. Since the `findByName` on our side is only executed on Gradle 7.x there is nothing to do here other than waiting for a future Gradle version changing this behavior
