### ISSUE TITLE
Enable signing only when publishing to maven central

### ISSUE THREAD

**Issue by mxalbert1996** [vanniktech/gradle-maven-publish-plugin#585]
The repo in which I found this issue: https://github.com/mxalbert1996/jacoco-android-gradle-plugin

I'm not specifying signing information in my dev machine (it's only specified in CI), but I need to run integration tests which need the artifacts to be published to local repository.

IIRC this used to work if I specify `RELEASE_SIGNING_ENABLED=false`, but now if I do that (or don't specify anything at all), the artifacts are not signed even when being published to maven central in CI, where the signing information is specified:
```
> Closing the repository failed with the following errors:
⠸ waiting for close...12 actionable tasks: 12 executed
  Missing Signature: '/com/mxalbert/gradle/jacoco-android/com.mxalbert.gradle.jacoco-android.gradle.plugin/0.2.0/com.mxalbert.gradle.jacoco-android.gradle.plugin-0.2.0.pom.asc' does not exist for 'com.mxalbert.gradle.jacoco-android.gradle.plugin-0.2.0.pom'.
  Missing Signature: '/com/mxalbert/gradle/jacoco-android/0.2.0/jacoco-android-0.2.0.module.asc' does not exist for 'jacoco-android-0.2.0.module'.
  Missing Signature: '/com/mxalbert/gradle/jacoco-android/0.2.0/jacoco-android-0.2.0-javadoc.jar.asc' does not exist for 'jacoco-android-0.2.0-javadoc.jar'.
  Missing Signature: '/com/mxalbert/gradle/jacoco-android/0.2.0/jacoco-android-0.2.0.pom.asc' does not exist for 'jacoco-android-0.2.0.pom'.
  Missing Signature: '/com/mxalbert/gradle/jacoco-android/0.2.0/jacoco-android-0.2.0-sources.jar.asc' does not exist for 'jacoco-android-0.2.0-sources.jar'.
  Missing Signature: '/com/mxalbert/gradle/jacoco-android/0.2.0/jacoco-android-0.2.0.jar.asc' does not exist for 'jacoco-android-0.2.0.jar'.
```

However if I specify `signAllPublications()`, I get this when I run integration tests on my dev machine:
```
Could not evaluate onlyIf predicate for task ':signJacocoAndroidGradlePluginPluginMarkerMavenPublication'.
> Could not evaluate spec for 'Signing is required, or signatory is set'.
```

So is there a way to enable signing only when publishing to maven central (or specified repos)?

**Comment by gabrielittner** [comment]
When you had `RELEASE_SIGNING_ENABLED=false` did you still call `signAllPublications()`? In that case signing would still get enabled because the explicit `signAllPublications()` takes precedence.

Generally there are a few ways how to manage this:
- Only use `RELEASE_SIGNING_ENABLED` and only set it to `true` in cases where you want to sign (e.g. set it on CI or if you are publishing from your local machine add `-PRELEASE_SIGNING_ENABLED=true` when calling publish)
- Something else that is commonly done is to keep the `VERSION_NAME` set to `...-SNAPSHOT` and only change it to a non snapshot version for the release (after the release bump the version and add -SNAPSHOT again). Even if signing is enabled through property or method, builds will not fail if signing is not set up locally if the version is a snapshot
