### ISSUE TITLE
Automate the release process

### ISSUE THREAD

**Issue by opensource21** [vanniktech/gradle-maven-publish-plugin#60]
As mentioned in #56  you must manually do the [release steps at sonatype](https://central.sonatype.org/pages/releasing-the-deployment.html).
It would be great to have this completely automated.

**Comment by martinbonnin** [comment]
Would it make sense to automate version bumps as well ? The plugin could drop the `-SNAPSHOT` suffix, make the release, bump version and add the `-SNAPSHOT` on the new version ? Basically automating the sed magic in https://github.com/square/okhttp/blob/master/RELEASING.md

**Comment by vanniktech** [comment]
I don't think we'd want this. I prefer being explicit than having some magic that alters version for you.

**Comment by martinbonnin** [comment]
Fair enough, I guess this can be automated via external scripts.

**Comment by martinbonnin** [comment]
I could look into this. 
Do we already have an idea how we would want to proceed ideally? Do we want to:

1. Depend on and configure https://github.com/Codearte/gradle-nexus-staging-plugin ?
or 
2. Add the logic and API calls in this repo ?

I could see 2. being more flexible, especially since the codearte plugin is all in groovy and I believe the audience here is more kotlin. So it would be nice to have everything in kotlin. But then that duplicates some logic? Any insights ?

**Comment by vanniktech** [comment]
> Do we also support bintray by changing releaseRepositoryUrl ?

Yeah.

I'd think we want to go with Option 2.

**Comment by martinbonnin** [comment]
> > Do we also support bintray by changing releaseRepositoryUrl ?
> 
> Yeah.
> 
> I'd think we want to go with Option 2.

Sounds good. Do we agree that the process of closing/releasing/dropping repositories is specific to Sonatype Nexus ? In that case it would make sense to add a separate task, right ? 

The workflow would be something like?

    ./gradlew uploadArchives
    ./gradlew promote

**Comment by vanniktech** [comment]
Sounds good

**Comment by gabrielittner** [comment]
It's now available in 0.9.0-SNAPSHOT
