### ISSUE TITLE
`publish` task fails if both snapshot and release `VERSION_NAME`(s) exist.

### ISSUE THREAD

**Issue by fornewid** [vanniktech/gradle-maven-publish-plugin#626]
First of all, thank you for making this plugin. I am using it well. :bow:

I'm developing [webtoon/ReadMoreTextView](https://github.com/webtoon/ReadMoreTextView) library.
In the following environment,
- gradle-maven-publish-plugin: `0.25.1`
- gradle: `8.1.1`

`publish` task fails if both snapshot and release exist.
```properties
# readmore-foundation/gradle.properties
VERSION_NAME=1.4.2

# readmore-view/gradle.properties
VERSION_NAME=1.3.3-SNAPSHOT
```

I am getting an error. (=`Staging repositories are not supported for SNAPSHOT versions.`)

> https://github.com/webtoon/ReadMoreTextView/actions/runs/5838761690/job/15836325405#step:7:195
> ```
> * What went wrong:
> Execution failed for task ':readmore-view:publishMavenPublicationToMavenCentralRepository'.
> > Staging repositories are not supported for SNAPSHOT versions.
> ```

It's an issue that hasn't happened before.
I am wondering if there is any way to solve it.

**Expected Behavior:**
Libraries must be published as releases, excluding `SNAPSHOT` version modules.

**Comment by gabrielittner** [comment]
The plugin makes the assumption that everything is published together and this a safety check for that. One issue that we want to avoid with that is accidentally publishing only half of a project to central and the rest as snapshots while these depend on each other. 

Since `readmore-view` is independent from what you're publishing that wouldn't be an issue for you. One thing that you could do is have separate publish invovations on CI. So instead of `./gradlew publish` you do `./gradlew readmore-view:publish` and separately `./gradlew readmore-foundation:publish readmore-material:publish readmore-material3:publish` (they can still be in the same job). That should get around this. The safety check would also make sure that you didn't forget to change the version of one of the 3 compose libraries when publishing.

**Comment by fornewid** [comment]
I understand that this is intended behavior.
Thanks for your comments.
