### ISSUE TITLE
Plugin fails when trying to make publish to both Maven Central and Maven Github Package Repository

### ISSUE THREAD

**Issue by RotBolt** [vanniktech/gradle-maven-publish-plugin#634]
Stack trace

```
FAILURE: Build failed with an exception.
> Task :library:flaker-android:javaDocReleaseJar UP-TO-DATE
> Task :library:flaker-android:sourceReleaseJar UP-TO-DATE
* What went wrong:
> Task :library:flaker-android:generateMetadataFileForMavenPublication
Execution failed for task ':library:flaker-android:signMavenPublication'.
> Task :library:flaker-android:generatePomFileForMavenPublication
> Cannot perform signing task ':library:flaker-android:signMavenPublication' because it has no configured signatory
> Task :library:flaker-android:signMavenPublication FAILED
90 actionable tasks: 3 executed, 87 up-to-date
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org/
BUILD FAILED in 5s
Error: Process completed with exit code 1.
```

This happens for me when I have both maven repositories configured for publishing
It passes for Maven Central but for Maven Github Packages it fails.

If I only keep one repository for publishing then it works fine

To me it seems like Maven Central Configuration is forcing `signing task` on Github Package Repository

I have done the setup of `Maven Central` through gradle properties

**Comment by gabrielittner** [comment]
Without seeing the project, this seems like the intentional behavior. When you enable release signing it is enabled for anything and will fail if signing credentials are not set up. The only exception to that is when the version ends with `-SNAPSHOT`.

Assuming that release signing is enabled in the failed Github Packages upload you have a few options:
- just also have the signing credentials available when uploading to Github packages so that you also upload signed artifacts there
- explicitly disable release signing when uploading to Github Packages, if you're using the `RELEASE_SIGNING_ENABLED` property this is as easy as adding `-PRELEASE_SIGNING_ENABLED=false` to the command that publishes to Github
- do the opposite of the above and disable signing by default and only enable it when publishing ot Maven Central by passing `-PRELEASE_SIGNING_ENABLED=true` to the command

**Comment by RotBolt** [comment]
>explicitly disable release signing when uploading to Github Packages, if you're using the RELEASE_SIGNING_ENABLED property this is as easy as adding -PRELEASE_SIGNING_ENABLED=false to the command that publishes to Github

Hey @gabrielittner thanks for replying
Just one more question, the flag you mentioned its for `PRE-RELEASE`, but I want to release those to Github maven repo so how does this help

For the repo, its an open source repo: https://github.com/RotBolt/Flaker

**Comment by gabrielittner** [comment]
@RotBolt It looks a bit missleading, Gradle's syntax for passing a Gradle property is `-P<name>=<value>`. Since the name of the property is `RELEASE_SIGNING_ENABLED` it then becomens `-PRELEASE_SIGNING_ENABLED=...`. An alternative to this syntax is setting an environment variable like this in your action `ORG_GRADLE_PROJECT_RELEASE_SIGNING_ENABLED=false` that will also override your default `RELEASE_SIGNING_ENABLED` from gradle.properties.

**Comment by RotBolt** [comment]
> just also have the signing credentials available when uploading to Github packages so that you also upload signed artifacts there

How can I have signing creds enabled/available for github packages? 

This I tried to look into but could not find anything.

**Comment by RotBolt** [comment]
> just also have the signing credentials available when uploading to Github packages so that you also upload signed artifacts there

@gabrielittner 
How can I have signing creds enabled/available for github packages? 

This I tried to look into but could not find anything.
