### ISSUE TITLE
Ideas for improving the release process tasks

### ISSUE THREAD

**Issue by sschuberth** [vanniktech/gradle-maven-publish-plugin#692]
Currently, it seems a bit awkward to me that the tasks to publish to Maven Central in any case already close the staging repository, but the (supposed to be?) complementing task is called "*closeAnd*ReleaseRepository". The obvious first question from a new user probably is: Why would I want to close my staging repository again, and why is there no "releaseRepository" only task?

Also, controlling the auto-release feature of the publish tasks via a property named `SONATYPE_AUTOMATIC_RELEASE` (which, due to its casing, looks more like an environment variable, BTW) is not very transparent, IMO.

To make this more consistent, I propose to drop the `closeAndReleaseRepository` task and instead teach the publish task to take task options named `--publish`, `--close`, and `--release` (maybe `--close` could be omitted if `--publish` is supposed to always close). That way, these options would show up with `./gradlew help --task publishTask`.

**Comment by gabrielittner** [comment]
I definitely agree that this is an area that can be further improved.

> Currently, it seems a bit awkward to me that the tasks to publish to Maven Central in any case already close the staging repository, but the (supposed to be?) complementing task is called "closeAndReleaseRepository". The obvious first question from a new user probably is: Why would I want to close my staging repository again, and why is there no "releaseRepository" only task?

This is mostly a historical leftover from before we had the automatic closing at the end of each build that runs `publish`. So like you said in practice the task will actually skip the closing part and just release the repository. So renaming the task to `releaseRepository` definitely makes sense (or adding it as a second task and deprecating the old one).

> Also, controlling the auto-release feature of the publish tasks via a property named SONATYPE_AUTOMATIC_RELEASE (which, due to its casing, looks more like an environment variable, BTW) is not very transparent, IMO.

The other way to control it is by passing `true` as second parameter to `publishToMavenCentral` to permanently turn it on. The casing is for consistency with other properties and comes from the original 10+ year old script that this plugin is based on. We can also start introducing aliases that use camel case.

> To make this more consistent, I propose to drop the closeAndReleaseRepository task and instead teach the publish task to take task options named --publish, --close, and --release (maybe --close could be omitted if --publish is supposed to always close). That way, these options would show up with ./gradlew help --task publishTask.

Unfortunately we can't teach the publish task anything since it's coming from Gradle and as far as I know you can't dynamically add options to an existing task class. Not using the default tasks would mean duplicating all the uploading logic that Gradle comes with. 

Maybe an option would be to have a `publishAndRelease` task and/or allowing to run `publish` and `releaseRepository` in the same build.

**Comment by gabrielittner** [comment]
I've opened 2 prs to improve this, happy to receive some feedback.

**Comment by sschuberth** [comment]
On a semi-related topic, I'm currently trying to disable signing when running `publishToMavenLocal`, but doing it like

    ./gradlew -P RELEASE_SIGNING_ENABLED=false publishToMavenLocal

seems to have no effect

    Cannot perform signing task ':clients:nexus-iq-client:signMavenPublication' because it has no configured signatory

**Comment by gabrielittner** [comment]
Closing this since the imporvements were done in the last release.
