### ISSUE TITLE
Explicitly creating and automatically closing staging repositories prevents publishing KMP libraries from multiple hosts

### ISSUE THREAD

**Issue by MSDarwish2000** [vanniktech/gradle-maven-publish-plugin#707]
In CI workflows, it is common practice to build non-Apple artifacts on a Linux runner which is usually cheaper and faster and build Apple artifacts on a MacOS runner. 

I, along with other reputable libraries like [SQLDelight](https://github.com/cashapp/sqldelight), use this pattern. This pattern worked fine with this plugin before v0.22.0, but the behavior change of automatically closing the staging repository made it impossible to publish a KMP library safely this way as artifacts gets into two (or more) separate staging repositories.

I misunderstood the changelog of the release resulting in broken library releases. Also, SQLDelight blocked version updates beyond v0.20.0 for this reason as seen in cashapp/sqldelight#3754.

I think adding an option to prevent this behavior wouldn't break anything for current release users, and would allow KMP library developers to get full use of this awesome plugin.

Possible duplicate of: #562

**Comment by MSDarwish2000** [comment]
Still, I'm not sure if this option is enough to allow this workflow to work properly. You may tell me more

**Comment by gabrielittner** [comment]
Having multiple staging repositories could have happened before as well and was actually a common issue. Before oss.sonatype.org would automatically create a staging repository and whether it reuses an existing one or creates a new one is not really controllable. So on older versions you might be lucky that everything lands in one staging repository most of the time but there is no guarantee.

> This pattern worked fine with this plugin before v0.22.0, but the behavior change of automatically closing the staging repository made it impossible to publish a KMP library safely this way as artifacts gets into two (or more) separate staging repositories.
> I misunderstood the changelog of the release resulting in broken library releases.

Closing repositories automatically shouldn't make releases more or less safe or increase the risk of broken releases. The plugin will create and close staging repositories automatically, thats it. The release step is not done automatically and if you want to publish something produced by multiple CI jobs in one go, you can then manually release them at the same time on the Sonatype website. 

The only thing that risks broken releases would be enabling automatic releases because then you could have one released repository, while the second CI job fails. 

> Also, SQLDelight blocked version updates beyond v0.20.0 for this reason as seen in https://github.com/cashapp/sqldelight/pull/3754.

I think it's more of a thing of having to take the time to update the ci workflow rather than being actually blocked to update. Other cashapp multiplatform libraries like https://github.com/cashapp/redwood or https://github.com/cashapp/molecule are on the latest version. However they do that by publishing from macOS.

**Comment by MSDarwish2000** [comment]
@gabrielittner Thank you for taking the time to reply. Sorry if I've made wrong assumptions.

I've decided to use macOS as a single host for now.

I was afraid to manually release multiple staging repositories at once to avoid irreversible damage and I wasn't able to find information about doing so online. Would you mind confirming that the release would be fine if I've done so, or reference a relevant documentation or resource?

Also, it would be a good idea if you considered supporting this situation. For example, by allowing adding a profile id and opt-out option for automatically closing the repo. Still, I don't have enough experience in Maven, so you know better.

I'll be closing this for now.
