### ISSUE TITLE
Gradle plugin markers do not contain pom packaging in some cases

### ISSUE THREAD

**Issue by rubensousa** [vanniktech/gradle-maven-publish-plugin#841]
I just spent quite some time figuring out why my plugin wasn't being found through mavenLocal in a separate project.
Turns out that the marker artifact generated by this plugin is missing this in the POM file if I specify `pom.packaging=jar` for the plugin

```
<packaging>pom</packaging>
```

This should be enough to reproduce:

```
group = "com.example.group"
version = "1.0.0"

gradlePlugin {
    plugins {
        register("plugin") {
            id = "com.example.group"
            implementationClass = "com.example.x.y.Plugin"
        }
    }
}

mavenPublishing {
    configure(
        GradlePlugin(
            javadocJar = JavadocJar.Javadoc(),
            sourcesJar = true
        )
    )
    coordinates(artifactId = "my-plugin")
    pom {
        packaging = "jar"
    }
}
```

If I remove `packaging = "jar"`  then I get this in the marker POM:

```
<packaging>pom</packaging>
```

However, doing that removes the jar packaging from the plugin's artifact POM file:

```
<packaging>jar</packaging>
```

Let me know if you need more information and if this is intended.

**Comment by rubensousa** [comment]
Looks like the plain `maven-publish` plugin also behaves like this, so this could be the expected structure. Anyway, would be great if we could mention this in the docs to avoid mistakes. If someone specifies `packaging = "jar"`  the setup gets broken

**Comment by gabrielittner** [comment]
I'll add a warning to the docs. Generally the packaging comes from the published component, so for example when publishing an Android library the component will automatically cause `packaging` to be set to `aar`. I assume Gradle doesn't add `<packaging>jar</packaging>` explicitly because the [POM spec](https://maven.apache.org/pom.html#packaging) says that `jar` will be used if `packaging` is not explicitly specified.
